<?php

namespace Acme\helloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlumnosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumnosRepository extends EntityRepository
{

    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AcmehelloBundle:Alumnos p  WHERE p.id = :id ORDER BY p.nombre DESC'
            )->setParameter('id','322')->getResult();
    }
}
